import { createHash } from 'node:crypto'
import { readdir, readFile, stat } from 'node:fs/promises'
import { join, relative, sep } from 'node:path'

export const SHELL_CACHE_PREFIX = 'livetrafficstan-shell-'
export const SHELL_BUDGET_BYTES = 4 * 1024 * 1024

const PUBLIC_SHELL_PATHS = [
  '/manifest.webmanifest',
  '/favicon.svg',
  '/icons/livetrafficstan-192-v1.png',
  '/icons/livetrafficstan-512-v1.png',
]

const toUrlPath = (path) => `/${path.split(sep).join('/')}`

const filesBelow = async (directory) => {
  const entries = await readdir(directory, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) {
      files.push(...(await filesBelow(path)))
    } else if (entry.isFile()) {
      files.push(path)
    }
  }
  return files.sort()
}

const shellEntry = async (distDirectory, url, filePath) => {
  const absolutePath = join(distDirectory, filePath)
  const bytes = await readFile(absolutePath)
  return {
    url,
    filePath: absolutePath,
    size: bytes.byteLength,
    digest: createHash('sha256').update(bytes).digest('hex'),
  }
}

export const collectShellEntries = async (distDirectory) => {
  const assetDirectory = join(distDirectory, 'assets')
  const assetFiles = await filesBelow(assetDirectory)
  const entries = [
    await shellEntry(distDirectory, '/', 'index.html'),
    await shellEntry(distDirectory, '/index.html', 'index.html'),
  ]

  for (const publicPath of PUBLIC_SHELL_PATHS) {
    entries.push(
      await shellEntry(distDirectory, publicPath, publicPath.slice(1)),
    )
  }
  for (const assetFile of assetFiles) {
    const filePath = relative(distDirectory, assetFile)
    entries.push(
      await shellEntry(distDirectory, toUrlPath(filePath), filePath),
    )
  }

  return entries.sort((left, right) => left.url.localeCompare(right.url))
}

const serviceWorkerPolicySource = () =>
  [
    classifyShellRequest.toString(),
    ownedCachesToDelete.toString(),
    renderServiceWorker.toString(),
  ].join('\0')

export const shellVersion = (
  entries,
  policySource = serviceWorkerPolicySource(),
) => {
  const hash = createHash('sha256')
  hash.update(policySource)
  hash.update('\0')
  for (const entry of entries) {
    hash.update(entry.url)
    hash.update('\0')
    hash.update(entry.digest)
    hash.update('\0')
  }
  return hash.digest('hex').slice(0, 20)
}

export const shellSize = (entries) =>
  entries.reduce((total, entry) => total + entry.size, 0)

export const classifyShellRequest = ({
  method,
  requestUrl,
  origin,
  mode,
  currentShellPaths,
}) => {
  if (method !== 'GET') return 'bypass'
  const url = new URL(requestUrl)
  if (url.origin !== origin) return 'bypass'
  if (
    mode === 'navigate' &&
    (url.pathname === '/' || url.pathname === '/index.html')
  ) {
    return 'navigation'
  }
  if (url.search) return 'bypass'
  if (
    currentShellPaths.includes(url.pathname) ||
    url.pathname.startsWith('/assets/')
  ) {
    return 'shell'
  }
  return 'bypass'
}

export const ownedCachesToDelete = (
  cacheNames,
  currentCacheName,
  predecessorCacheName,
  cachePrefix = SHELL_CACHE_PREFIX,
) => {
  const owned = cacheNames.filter((name) => name.startsWith(cachePrefix))
  const predecessor =
    predecessorCacheName !== currentCacheName &&
    owned.includes(predecessorCacheName)
      ? predecessorCacheName
      : undefined
  const retained = new Set(
    [currentCacheName, predecessor].filter(Boolean),
  )
  return owned.filter((name) => !retained.has(name))
}

export const renderServiceWorker = ({ version, urls }) => {
  const cacheName = `${SHELL_CACHE_PREFIX}${version}`
  return `/* Generated by scripts/generate-service-worker.mjs. */
const SHELL_CACHE_PREFIX = ${JSON.stringify(SHELL_CACHE_PREFIX)};
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_URLS = ${JSON.stringify(urls, null, 2)};
const CURRENT_SHELL_PATHS = new Set(PRECACHE_URLS);
const ACTIVE_CACHE_HEADER = 'x-livetrafficstan-active-cache';
const PREDECESSOR_CACHE_HEADER = 'x-livetrafficstan-predecessor-cache';
let activationAuthorized = false;

const classifyShellRequest = ${classifyShellRequest.toString()};
const ownedCachesToDelete = ${ownedCachesToDelete.toString()};

const cacheMetadata = async (cacheName, headerName) => {
  const response = await (await caches.open(cacheName)).match('/');
  return response?.headers.get(headerName) ?? undefined;
};

const writeCacheMetadata = async (
  cacheName,
  { active, predecessor } = {},
) => {
  const cache = await caches.open(cacheName);
  const response = await cache.match('/');
  if (!response) {
    throw new Error('Application-shell cache is missing its root response');
  }
  const headers = new Headers(response.headers);
  if (active !== undefined) {
    if (active) headers.set(ACTIVE_CACHE_HEADER, '1');
    else headers.delete(ACTIVE_CACHE_HEADER);
  }
  if (predecessor !== undefined) {
    if (predecessor) {
      headers.set(PREDECESSOR_CACHE_HEADER, predecessor);
    } else {
      headers.delete(PREDECESSOR_CACHE_HEADER);
    }
  }
  await cache.put('/', new Response(await response.arrayBuffer(), {
    status: response.status,
    statusText: response.statusText,
    headers,
  }));
};

const findActiveCacheName = async () => {
  const owned = (await caches.keys())
    .filter(
      (name) =>
        name !== CACHE_NAME &&
        name.startsWith(SHELL_CACHE_PREFIX),
    )
    .reverse();
  for (const cacheName of owned) {
    if (
      (await cacheMetadata(cacheName, ACTIVE_CACHE_HEADER)) === '1'
    ) {
      return cacheName;
    }
  }
  return undefined;
};

const ownedCacheNamesCurrentFirst = async () => {
  const owned = (await caches.keys())
    .filter((name) => name.startsWith(SHELL_CACHE_PREFIX));
  return [
    CACHE_NAME,
    ...owned.reverse().filter((name) => name !== CACHE_NAME),
  ];
};

const matchOwnedCache = async (request) => {
  for (const cacheName of await ownedCacheNamesCurrentFirst()) {
    const response = await (await caches.open(cacheName)).match(request);
    if (response) return response;
  }
  return undefined;
};

const navigationResponse = async (request) => {
  try {
    return await fetch(request);
  } catch (error) {
    const fallback = await matchOwnedCache('/index.html');
    if (fallback) return fallback;
    throw error;
  }
};

const shellResponse = async (request) =>
  (await matchOwnedCache(request)) ?? fetch(request);

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const existingCacheNames = await caches.keys();
    const cacheAlreadyExists = existingCacheNames.includes(CACHE_NAME);
    let cacheWasCreated = !cacheAlreadyExists;
    let cache = await caches.open(CACHE_NAME);
    try {
      if (cacheAlreadyExists) {
        const existing = await Promise.all(
          PRECACHE_URLS.map((url) => cache.match(url)),
        );
        if (!existing.every(Boolean)) {
          const incompleteCacheIsActive =
            (await cacheMetadata(CACHE_NAME, ACTIVE_CACHE_HEADER)) === '1';
          if (incompleteCacheIsActive) {
            throw new Error(
              'Active application-shell cache is incomplete',
            );
          }
          await caches.delete(CACHE_NAME);
          cache = await caches.open(CACHE_NAME);
          cacheWasCreated = true;
          await cache.addAll(PRECACHE_URLS);
        }
      } else {
        await cache.addAll(PRECACHE_URLS);
      }
      const cacheIsActive =
        (await cacheMetadata(CACHE_NAME, ACTIVE_CACHE_HEADER)) === '1';
      if (!cacheIsActive) {
        await writeCacheMetadata(CACHE_NAME, {
          active: false,
          predecessor: (await findActiveCacheName()) ?? null,
        });
      }
    } catch (error) {
      if (cacheWasCreated) await caches.delete(CACHE_NAME);
      throw error;
    }
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type !== 'ACTIVATE_UPDATE') return;
  activationAuthorized = true;
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const cacheNames = await caches.keys();
    const recordedPredecessor = await cacheMetadata(
      CACHE_NAME,
      PREDECESSOR_CACHE_HEADER,
    );
    const predecessor =
      recordedPredecessor &&
      recordedPredecessor !== CACHE_NAME &&
      cacheNames.includes(recordedPredecessor) &&
      recordedPredecessor.startsWith(SHELL_CACHE_PREFIX)
        ? recordedPredecessor
        : undefined;
    await writeCacheMetadata(CACHE_NAME, { active: true });
    if (predecessor) {
      await writeCacheMetadata(predecessor, { active: false });
    }
    await Promise.all(
      ownedCachesToDelete(
        cacheNames,
        CACHE_NAME,
        predecessor,
        SHELL_CACHE_PREFIX,
      )
        .map((name) => caches.delete(name)),
    );
    if (activationAuthorized) {
      await self.clients.claim();
    }
  })());
});

self.addEventListener('fetch', (event) => {
  const kind = classifyShellRequest({
    method: event.request.method,
    requestUrl: event.request.url,
    origin: self.location.origin,
    mode: event.request.mode,
    currentShellPaths: [...CURRENT_SHELL_PATHS],
  });
  if (kind === 'navigation') {
    event.respondWith(navigationResponse(event.request));
  } else if (kind === 'shell') {
    event.respondWith(shellResponse(event.request));
  }
});
`
}

export const renderRetirementServiceWorker = () => `/* LiveTrafficStan PWA retirement worker. */
const CACHE_PREFIX = ${JSON.stringify(SHELL_CACHE_PREFIX)};

self.addEventListener('install', (event) => {
  event.waitUntil(self.skipWaiting());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const cacheNames = await caches.keys();
    await Promise.all(
      cacheNames
        .filter((name) => name.startsWith(CACHE_PREFIX))
        .map((name) => caches.delete(name)),
    );
    await self.registration.unregister();
    const windows = await self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    });
    for (const client of windows) {
      client.postMessage({ type: 'APP_SHELL_RETIRED' });
    }
    await new Promise((resolve) => setTimeout(resolve, 100));
    await Promise.all(
      windows.map((client) =>
        client.navigate(client.url).catch(() => undefined),
      ),
    );
  })());
});
`

export const assertShellBudget = (
  entries,
  budgetBytes = SHELL_BUDGET_BYTES,
) => {
  const total = shellSize(entries)
  if (total > budgetBytes) {
    throw new Error(
      `Application shell is ${total} bytes; budget is ${budgetBytes} bytes`,
    )
  }
  return total
}

export const verifyShellFiles = async (entries) => {
  for (const entry of entries) {
    const info = await stat(entry.filePath)
    if (!info.isFile()) {
      throw new Error(`Shell entry is not a file: ${entry.filePath}`)
    }
  }
}
